server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/rodrigo/Documents/VOffice/Microservices/workshop-microservices/sources/cloud-lab01-sol/config-repo