server:
  port: ${PORT:9000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
    
spring:
  cloud:
    dashboard:
      http:
        # Basic Credentials
        username: user
        password: password
        
        # Optional Defaults values
        maxConnection: 100 
    connectTimeout: 1000
    socketTimeout: 2000 
    requestTimeout: 1000    