server:
  port: ${PORT:9000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
    
spring:
  boot:
    admin:
      url: http://localhost:9000
      username: admin
      password: t0ps3cr3t  