server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

logging:
  level: debug

---
spring:
  profiles: docker

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server:8761/eureka}
 instance:
   preferIpAddress: true  
