server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/rcandidosilva/workshop-microservices.git
          search-paths: sources/docker-lab03-sol/config-repo        
  rabbitmq:
    host: localhost
    port: 5672    
    
security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM